package com.gordondickens.sijms;

import org.springframework.integration.annotation.Gateway;
import org.springframework.integration.annotation.Header;


/**
 * This is a simple Spring Integration Gateway interface
 * The implementation class will be generated by Spring Integration
 * Annotate Methods with @Gateway, and optionally annotate inbound parameters
 * to be added to the @Header of the message
 * 
 * @author Gordon Dickens
 *
 */
//@Component("myJmsGateway")
public interface MyJmsGateway {
    @Gateway
	public void sendMyMessage(@Header("myHeaderKey") String s, Object o);

}
